openapi: 3.0.0
info:
  title: Attendance and Salary Management API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  $ref: './paths.yml'
components:
  schemas:
    $ref: './schemas.yml'
